Add not support for holdings
NelsonDane/auto-rsa pull request #280
Opened 2024-07-05 18:34 UTC by matthew55

As it is right now, it is not possible to use `not` for holdings. This PR makes it easier when dealing with issues such as #275 to run `!rsa holdings all not chase`.

2024-07-05 18:38 UTC, matthew55 commented
Also, unrelated but later on in the file `autoRSA.py` there is the code sample:
```python
        if not orderObj.get_holdings():
            printAndDiscord("All transactions complete in all brokers", loop)
```
which prevents a message from showing that holdings command has finished to completion. Can I remove the check preventing a holdings completion message?

2024-07-05 19:29 UTC, NelsonDane commented
> Also, unrelated but later on in the file `autoRSA.py` there is the code sample:
> 
> ```python
>         if not orderObj.get_holdings():
>             printAndDiscord("All transactions complete in all brokers", loop)
> ```
> 
> which prevents a message from showing that holdings command has finished to completion. Can I remove the check preventing a holdings completion message?

You're good to remove that, I would just change the wording to something like "All commands complete in all brokers" instead of the word "transactions". It was there since very often holdings was often 1 account but it makes sense to print a completed.

2024-07-06 17:24 UTC, matthew55 commented
Should be ready for a review and merge.

2024-07-07 18:27 UTC, NelsonDane requested changes

2024-07-07 18:27 UTC, NelsonDane commented on autoRSA.py
> +
Looks good, can you remove the newlines on 184 and 190 to match the rest of the function?

2024-07-07 19:27 UTC, NelsonDane approved these changes
Awesome, thanks so much!

2024-07-07 19:27 UTC, merged