dSPAC Support
NelsonDane/auto-rsa pull request #353
Opened 2024-09-02 07:37 UTC by ImNotOssy

ofc you need 
https://github.com/ImNotOssy/dSPAC_investing_API

"dspac_investing_API"
folder inside for it to work

2024-09-08 02:40 UTC, MaxxRK commented on .env.example
> +
As NelsonDane mentioned in BBAE I would remove the TRUE/FALSE if possible and just determine whether it's an email using a simple check such as '@'. Any option would work there.

2024-09-08 02:42 UTC, MaxxRK requested changes
This looks great for the most part. It now works for me. The comment above and below are the only changes needed that I see right now.

2024-09-08 03:01 UTC, MaxxRK commented on dspacAPI.py
> +            ds = DSPACAPI(user, password, filename=f"DSPAC_{index + 1}.txt", creds_path="./creds/")
Nelson Dane also mentioned this, but the creds file should be saved as a .pkl or json.

2024-09-18 17:46 UTC, MaxxRK commented
I used this today and I believe its ready to merge.

2024-09-21 22:53 UTC, NelsonDane approved these changes
LGTM

2024-09-22 00:04 UTC, MaxxRK approved these changes
Looks Good!

2024-09-22 00:04 UTC, merged